### ISSUE TITLE
RedisClusterActor fails to choose a correct node

### ISSUE THREAD

**Issue by kobkaz** [Idein/actix-redis-cluster#2] opened 2019-02-21 07:25 UTC
I found that this test is not working as intended. https://github.com/Idein/actix-redis-cluster/blob/2dae07c2027edb08099b5b12c6941609df4d9ab7/tests/test_cluster.rs#L11

At the first request to the cluster here, https://github.com/Idein/actix-redis-cluster/blob/2dae07c2027edb08099b5b12c6941609df4d9ab7/tests/test_cluster.rs#L23-L27 ```RedisClusterActor::choose_node_addr``` doesn't find the correct node and the request is sent to a randomly selected node.
It seems that the ```self.slots``` is still empty at this point.

Despite this problem, the test passes because Redis cluster automatically redirects the request.

**Comment by pandaman64** [comment] 2019-02-21 08:01
I don't think Redis cluster nodes (servers) redirect the requests as mentioned in the [spec](https://redis.io/topics/cluster-spec#clients-and-servers-roles-in-the-redis-cluster-protocol):
> Since cluster nodes are not able to proxy requests, clients may be redirected to other nodes using redirection errors -MOVED and -ASK. The client is in theory free to send requests to all the nodes in the cluster, getting redirected if needed, so the client is not required to hold the state of the cluster. However clients that are able to cache the map between keys and nodes can improve the performance in a sensible way.

These redirections are handled here: https://github.com/Idein/actix-redis-cluster/blob/2dae07c2027edb08099b5b12c6941609df4d9ab7/src/cluster.rs#L348-L425

In the test case, `self.slots` is empty when the first command is issued as you observed, but it's okay because `RedisClusterActor` can handle the `MOVED` redirection and re-request from the appropriate node.
Though this behavior is not optimal, I don't think this is a huge problem because the slot configuration should become stable quickly.

**Comment by kobkaz** [comment] 2019-02-21 09:28
I want this issue fixed because it affects Lua-related features I am developing in #1.

Unfortunately, Redis cluster doesn't share scripts among master nodes (Yet I haven't found any official document which states this).
Thus, when you send ```SCRIPT LOAD``` to a wrong node, it will just succeed silently without ```MOVED``` response, but the script will not be loaded to the correct node.

**Comment by pandaman64** [comment] 2019-02-21 13:19
Ah, so the problem is how to load Lua scripts into the appropriate node, right?
Now it does make sense.
I thought you intended to load the script into the target node by specifying the same `slot` in `ScriptLoad` as those of the keys. Doesn't it work?
https://github.com/NogikuchiKBYS/actix-redis-cluster/blob/ff915e37121bedba35e27d21e342c988129eb4bd/src/command.rs#L619

**Comment by pandaman64** [comment] 2019-02-21 13:30
I'll see how other implementations treat scripts...

**Comment by pandaman64** [comment] 2019-02-22 02:13
LINE seems to be not using `SCRIPT LOAD` at all
https://engineering.linecorp.com/ja/blog/redis-lua-scripting-atomic-processing-cache/

**Comment by pandaman64** [comment] 2019-02-22 02:20
Jedis looks like doing similar (taking a sample key for `SCRIPT LOAD`):
https://github.com/xetorthio/jedis/blob/6ed1441ca4c5de7e66648edfeafa16854707482c/src/main/java/redis/clients/jedis/JedisCluster.java#L1825

**Comment by pandaman64** [comment] 2019-02-22 02:40
ioredis has some trickery for automatically caching scripts but I have not figured out how they are doing that:
https://github.com/luin/ioredis/blob/6049f6c9aa852c89efdc32dda755ea7f7a7a51fd/README.md#lua-scripting

They check whether the script has been already loaded just before executing it:
https://github.com/luin/ioredis/blob/master/lib/pipeline.ts#L265

**Comment by kobkaz** [comment] 2019-02-26 09:49
Yes, my approach is similar to that of Jedis.
I wrote actual failing examples in #1.

**Comment by pandaman64** [comment] 2019-04-11 07:24
fixed by c10cd196099817ba21267df9e8318447d1637bd1, but it drops pipelining...

**Closed as completed by pandaman64** 2019-04-11 07:24 UTC
